name: Build Tweak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Theos dependencies
        run: |
          brew install ldid dpkg make perl
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p packages
          THEOS_PACKAGE_SCHEME=rootless gmake clean package FINALPACKAGE=1 -j8
          mv packages/com.lain.amoleddnevnik_*_iphoneos-arm64e.deb packages/AmoledDnevnik.rootless.deb
          rm -rf $HOME/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)" -H "Authorization: token $GITHUB_TOKEN"
          THEOS_PACKAGE_SCHEME=roothide gmake clean package FINALPACKAGE=1 -j8
          mv packages/com.lain.amoleddnevnik_*_iphoneos-arm64e.deb packages/AmoledDnevnik.roothide.deb
          rm -rf $HOME/theos
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          gmake clean package FINALPACKAGE=1 -j8
          mv packages/com.lain.amoleddnevnik_*_iphoneos-arm64e.deb packages/AmoledDnevnik.rootful.deb
          cd packages && zip AmoledDnevnik.zip *.deb

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: AmoledDnevnik
          path: ./packages/AmoledDnevnik.zip
