name: Build Tweak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Theos dependencies
        run: |
          brew install ldid dpkg make perl
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build .deb package
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload .deb to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AmoledDnevnik.deb
          path: ./packages/*.deb
